[build-system]
requires = [
    "setuptools>=64",
    "setuptools_scm>=8",
    "cython>=3.0",
    "cmake",
    "numpy>=1.26.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyopenjtalk-ndy"
dynamic = ["version"]
description = "A python wrapper for OpenJTalk"
readme = "README.md"
requires-python = ">=3.10"
license.file = "LICENSE.md"
authors = [{ name = "Ryuichi Yamamoto", email = "zryuichi@gmail.com" }]
keywords = ["OpenJTalk", "Research"]
classifiers = [
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Cython",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
]
urls.Homepage = "https://github.com/r9y9/pyopenjtalk"
dependencies = [
    "numpy>=1.26.0",
    "tqdm",
]

[project.optional-dependencies]
docs = [
    "sphinx_rtd_theme",
    "nbsphinx>=0.8.6",
    "Jinja2>=3.0.1",
    "pandoc",
    "ipython",
    "jupyter",
]
dev = [
    "cython>=3.0",
    "pysen>=0.12.1",
    "types-setuptools",
    "mypy>=1.11",
    "black>=24.0",
    "flake8>=7.0",
    "flake8-bugbear>=24.0",
    "isort>=5.13,<8",
    "types-decorator",
]
test = ["pytest", "scipy"]
marine = ["marine>=0.0.5"]

[tool.setuptools.packages.find]
include = ["pyopenjtalk*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.pyx", "*.pxd"]

[tool.setuptools_scm]
version_file = "pyopenjtalk/version.py"
version_file_template = '''
__version__ = "{version}"
'''
# local_scheme = "no-local-version"

[tool.pysen]
version = "0.12.1"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false # TODO: enable mypy in the future
mypy_preset = "strict"
line_length = 88
py_version = "py310"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
